import type { ProviderConfig, ModelConfig } from "../router/types.js";
import type { ModelTier, TaskType } from "../router/task-types.js";
import type { ToolApprovalMode, ConnectorType } from "@sa/shared/types.js";

export interface Identity {
  name: string;
  personality: string;
  systemPrompt: string;
}

/** Per-connector tool approval configuration */
export type ToolApprovalConfig = Partial<Record<ConnectorType, ToolApprovalMode>>;

/** Tool reporting verbosity levels */
export type ToolVerbosity = "silent" | "minimal" | "verbose";

/** Per-tool override for danger level and reporting */
export interface ToolOverride {
  dangerLevel?: "safe" | "moderate" | "dangerous";
  report?: "always" | "never" | "on_error";
}

/** Tool policy configuration */
export interface ToolPolicyConfig {
  /** Per-connector reporting verbosity */
  verbosity?: Partial<Record<ConnectorType, ToolVerbosity>>;
  /** Per-tool overrides (danger level and/or reporting) */
  overrides?: Record<string, ToolOverride>;
}

/** Heartbeat configuration for the engine's periodic agent check */
export interface HeartbeatConfig {
  /** Whether the heartbeat is enabled (default: true) */
  enabled: boolean;
  /** Interval in minutes between heartbeat checks (default: 30) */
  intervalMinutes: number;
  /** Path to the heartbeat checklist file relative to SA_HOME (default: "HEARTBEAT.md") */
  checklistPath?: string;
  /** Token the agent returns to indicate nothing needs attention (default: "HEARTBEAT_OK") */
  suppressToken: string;
}

export interface RuntimeConfig {
  activeModel: string;
  telegramBotTokenEnvVar: string;
  memory: {
    enabled: boolean;
    directory: string;
  };
  /** Per-connector tool approval mode (default: "never" for tui, "ask" for IM connectors) */
  toolApproval?: ToolApprovalConfig;
  /** Webhook connector configuration */
  webhook?: {
    enabled: boolean;
    /** Shared secret for authenticating webhook requests */
    secret?: string;
  };
  /** Audio transcription configuration */
  audio?: {
    enabled: boolean;
    /** Prefer local Whisper over cloud API when both are available */
    preferLocal: boolean;
  };
  /** Plain (non-secret) environment variables injected at engine startup */
  env?: Record<string, string>;
  /** Map each model tier to a configured model name */
  modelTiers?: Partial<Record<ModelTier, string>>;
  /** Override the default task-to-tier mapping */
  taskTierOverrides?: Partial<Record<TaskType, ModelTier>>;
  /** Shorthand aliases for model names (e.g. { "fast": "haiku", "smart": "opus" }) */
  modelAliases?: Record<string, string>;
  /** Tool policy: per-connector verbosity and per-tool overrides */
  toolPolicy?: ToolPolicyConfig;
  /** Heartbeat configuration */
  heartbeat?: HeartbeatConfig;
}

/** On-disk config.json schema (v3 — merged models + runtime) */
export interface SAConfigFile {
  version: 3;
  runtime: RuntimeConfig;
  providers: ProviderConfig[];
  models: ModelConfig[];
  defaultModel: string;
}

/** Full in-memory config (identity from IDENTITY.md + everything else from config.json) */
export interface SAConfig {
  identity: Identity;
  runtime: RuntimeConfig;
  providers: ProviderConfig[];
  models: ModelConfig[];
  defaultModel: string;
}

export interface SecretsFile {
  /** Map of env var name → raw API key, e.g. { "ANTHROPIC_API_KEY": "sk-..." } */
  apiKeys: Record<string, string>;
  /** Raw Telegram bot token, if stored */
  botToken?: string;
  /** Telegram chat ID of the paired user — bot ignores all other senders */
  pairedChatId?: number;
  /** One-time pairing code generated by the wizard; user sends /pair <code> to activate filtering */
  pairingCode?: string;
  /** Raw Discord bot token, if stored */
  discordToken?: string;
  /** Discord guild (server) ID for bot operation */
  discordGuildId?: string;
}
