#!/usr/bin/env bun
/**
 * Reads all bundled SKILL.md files and generates a TypeScript module
 * that embeds their content as strings. This allows the built binary
 * to include bundled skills without needing the filesystem.
 */
import { readdir, readFile, stat } from "node:fs/promises";
import { join } from "node:path";

const BUNDLED_DIR = join(import.meta.dir, "..", "src", "engine", "skills", "bundled");
const OUTPUT = join(import.meta.dir, "..", "src", "engine", "skills", "embedded-skills.generated.ts");

const entries = await readdir(BUNDLED_DIR);
const skills: { name: string; content: string }[] = [];

for (const entry of entries) {
  const skillDir = join(BUNDLED_DIR, entry);
  const s = await stat(skillDir);
  if (!s.isDirectory()) continue;

  const skillFile = join(skillDir, "SKILL.md");
  try {
    const content = await readFile(skillFile, "utf-8");
    skills.push({ name: entry, content });
  } catch {
    // skip directories without SKILL.md
  }
}

skills.sort((a, b) => a.name.localeCompare(b.name));

const lines = [
  "// Auto-generated by scripts/embed-skills.ts — do not edit",
  "// prettier-ignore",
  "export const EMBEDDED_SKILLS: Record<string, string> = {",
];

for (const { name, content } of skills) {
  // Use JSON.stringify to safely escape the content
  lines.push(`  ${JSON.stringify(name)}: ${JSON.stringify(content)},`);
}

lines.push("};");
lines.push("");

await Bun.write(OUTPUT, lines.join("\n"));
console.log(`Embedded ${skills.length} skills into ${OUTPUT}`);
