#!/usr/bin/env bun
/**
 * Reads all bundled skill directories and generates a TypeScript module
 * that embeds their .md file content as strings. This allows the built binary
 * to include bundled skills (SKILL.md + docs/) without needing the filesystem.
 */
import { readdir, readFile, stat } from "node:fs/promises";
import { join, relative } from "node:path";

const BUNDLED_DIR = join(import.meta.dir, "..", "src", "engine", "skills", "bundled");
const OUTPUT = join(import.meta.dir, "..", "src", "engine", "skills", "embedded-skills.generated.ts");

interface SkillFiles {
  name: string;
  files: { path: string; content: string }[];
}

/** Recursively collect all .md files under a directory */
async function collectMdFiles(dir: string, baseDir: string): Promise<{ path: string; content: string }[]> {
  const results: { path: string; content: string }[] = [];
  const entries = await readdir(dir);

  for (const entry of entries) {
    const fullPath = join(dir, entry);
    const s = await stat(fullPath);

    if (s.isDirectory()) {
      const nested = await collectMdFiles(fullPath, baseDir);
      results.push(...nested);
    } else if (entry.endsWith(".md")) {
      const content = await readFile(fullPath, "utf-8");
      const relPath = relative(baseDir, fullPath);
      results.push({ path: relPath, content });
    }
  }

  return results;
}

const entries = await readdir(BUNDLED_DIR);
const skills: SkillFiles[] = [];

for (const entry of entries) {
  const skillDir = join(BUNDLED_DIR, entry);
  const s = await stat(skillDir);
  if (!s.isDirectory()) continue;

  const mdFiles = await collectMdFiles(skillDir, skillDir);
  if (mdFiles.length === 0) continue;

  skills.push({ name: entry, files: mdFiles });
}

skills.sort((a, b) => a.name.localeCompare(b.name));

const lines = [
  "// Auto-generated by scripts/embed-skills.ts — do not edit",
  "// prettier-ignore",
  "",
  "/** Map of skill name → { relative path → content } for all .md files in each bundled skill */",
  "export const EMBEDDED_SKILLS: Record<string, Record<string, string>> = {",
];

for (const { name, files } of skills) {
  lines.push(`  ${JSON.stringify(name)}: {`);
  for (const { path, content } of files.sort((a, b) => a.path.localeCompare(b.path))) {
    lines.push(`    ${JSON.stringify(path)}: ${JSON.stringify(content)},`);
  }
  lines.push("  },");
}

lines.push("};");
lines.push("");

await Bun.write(OUTPUT, lines.join("\n"));

const totalFiles = skills.reduce((sum, s) => sum + s.files.length, 0);
console.log(`Embedded ${totalFiles} files across ${skills.length} skills into ${OUTPUT}`);
